Const BOUNDARY_W=52
Const BOUNDARY_H=60
Const BOUNDARY_TRANSPARENCY#=0.2
Const BOUND_DEATHZONE_Y=-20

Global BOUND_LEFT
Global BOUND_RIGHT
Global BOUND_UP

Global BOUNDARY_BRICK_START_Y#
;~IDEal Editor Parameters:
;~C#Blitz3D